### ISSUE TITLE
Remove secrets from script

### ISSUE THREAD

**Issue by bgbak** [MThicklin/HN-headline-grabber#1]
Maybe remove the SMPT auth details from the uploaded script.
https://github.com/MThicklin/HN-headline-grabber/blob/30c8ec7c21a441136dd7de285c7f115accf48623/hn_news.py#L39

**Comment by MThicklin** [comment]
Sweet Mercy, that's a great idea!  Thank you very much!

I've moved the credentials and password to a new file and labeled them accordingly.
